# Generated by Django 2.1.3 on 2018-12-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidermodel',
            name='owner',
            field=models.IntegerField(db_index=True, help_text='分类ID或主题ID', verbose_name='拥有者ID'),
        ),
    ]
