# Generated by Django 2.1.3 on 2018-12-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20181207_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='spiderLogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField(default='空', verbose_name='信息')),
                ('log_type', models.IntegerField(choices=[(0, 'Info'), (1, 'Warnings'), (2, 'Errors')], verbose_name='日志类型')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='发生时间')),
                ('spider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.spiderModel')),
            ],
        ),
    ]
