# Generated by Django 2.1.3 on 2018-11-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('cover', models.URLField(default='', help_text='封面链接', null=True, verbose_name='封面链接')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categoryModel', verbose_name='分类')),
            ],
        ),
    ]
