# Generated by Django 2.1.3 on 2018-11-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
    ]
