# Generated by Django 2.1.3 on 2018-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20181122_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='state',
            field=models.IntegerField(choices=[(0, '热播中'), (1, '全集')], default=0, help_text='状态', verbose_name='状态'),
        ),
    ]
