# Generated by Django 2.1.3 on 2018-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20181122_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='desc',
            field=models.CharField(default='无', help_text='描述', max_length=500, verbose_name='描述'),
        ),
    ]
