# Generated by Django 2.1.3 on 2018-11-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_subjectmodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='tags',
            field=models.CharField(default='无', help_text='标签', max_length=250, verbose_name='标签'),
        ),
    ]
