# Generated by Django 2.1.3 on 2018-11-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_subjectmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='actress',
            field=models.CharField(default='无', help_text='演员', max_length=500, verbose_name='演员'),
        ),
    ]
