# Generated by Django 2.1.3 on 2018-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_auto_20181206_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='tips',
            field=models.CharField(default='', help_text='提示', max_length=30, verbose_name='提示'),
        ),
    ]
