# Generated by Django 2.1.3 on 2018-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_subjectmodel_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='douban_id',
            field=models.BigIntegerField(default=0, help_text='豆瓣ID', verbose_name='豆瓣ID'),
        ),
    ]
