# Generated by Django 2.1.3 on 2018-11-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='全集', help_text='视频名称', max_length=50, verbose_name='视频名称')),
                ('视频地址', models.URLField(default='', help_text='视频地址', verbose_name='视频地址')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.lineModel', verbose_name='线路')),
            ],
        ),
    ]
