# Generated by Django 2.1.3 on 2018-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20181122_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='player',
            field=models.IntegerField(default=0, help_text='播放器', verbose_name='播放器'),
        ),
    ]
