# Generated by Django 2.1.3 on 2018-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videomodel_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='link',
            field=models.URLField(default='', help_text='视频地址', max_length=4096, verbose_name='视频地址'),
        ),
    ]
