# Generated by Django 2.1.3 on 2018-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20181124_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='live',
            field=models.BooleanField(default=False, help_text='直播', verbose_name='直播'),
        ),
    ]
