# Generated by Django 2.1.3 on 2018-11-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_videomodel_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='add_time',
            field=models.DateTimeField(auto_now=True, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
