# Generated by Django 2.1.3 on 2018-11-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20181124_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='player',
            field=models.IntegerField(choices=[(0, 'DPlayer'), (1, 'ckPlayer'), (2, 'iframe')], default=0, help_text='播放器', verbose_name='播放器'),
        ),
    ]
