# Generated by Django 2.1.3 on 2018-11-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20181127_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='link',
            field=models.CharField(default='', help_text='视频地址', max_length=4096, verbose_name='视频地址'),
        ),
    ]
