# Generated by Django 2.1.3 on 2018-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20181127_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='order',
            field=models.IntegerField(default=999, help_text='排序', verbose_name='排序'),
        ),
    ]
