# Generated by Django 2.1.3 on 2018-12-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_videomodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='player',
            field=models.IntegerField(choices=[(0, 'DPlayer'), (1, 'ckPlayer'), (2, 'iframe'), (3, '站外链接')], default=0, help_text='播放器', verbose_name='播放器'),
        ),
    ]
