# Generated by Django 2.1.3 on 2018-12-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoparse', '0001_initial'),
        ('video', '0011_auto_20181207_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_parse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videoparse.videoParseModel', verbose_name='视频解析API'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='player',
            field=models.IntegerField(choices=[(0, 'DPlayer'), (1, 'ckPlayer'), (2, 'iframe'), (3, '站外链接'), (4, 'VIP解析')], default=0, help_text='播放器', verbose_name='播放器'),
        ),
    ]
