# Generated by Django 2.1.3 on 2018-11-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linemodel',
            options={'verbose_name': '播放线路', 'verbose_name_plural': '播放线路'},
        ),
    ]
