# Generated by Django 2.1.3 on 2018-12-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_auto_20181204_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemodel',
            name='internal_name',
            field=models.CharField(blank=True, default='', help_text='内部名称', max_length=50, verbose_name='内部名称'),
        ),
    ]
