# Generated by Django 2.1.3 on 2018-12-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_linemodel_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='internal_name',
            field=models.CharField(blank=True, default='', help_text='内部名称', max_length=50, unique=True, verbose_name='内部名称'),
        ),
    ]
