# Generated by Django 2.1.3 on 2018-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoParseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parse_link', models.CharField(default='', help_text='解析API', max_length=4096, verbose_name='解析API')),
            ],
        ),
    ]
