"""
Django settings for videsite project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
import datetime

DEBUG = True

ALLOWED_HOSTS = ['*']

# ------------------ 跨域配置 ------------------
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    'zfdev.com',
    '192.168.0.88:8080',
    '192.168.0.88:8081',
    '127.0.0.1:8081',
    '127.0.0.1:8080',
    '127.0.0.1:8000',
)
# CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'clienttype',
)
